# create the front-end for MooseKV
apiVersion: v1
kind: Pod
metadata:
  name: moose-frontend
  labels:
    app: moose-frontend
spec:
  containers:
  - name: moose-frontend
    image: buchuitoudegou/moosekv:frontend
    ports:
      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: moose-frontend-svc
spec:
  type:
    NodePort
  selector:
    app.kubernetes.io/name: moose-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000